<?php

/**
 * @file
 * Contains hook implementations.
 */


/**
 * Implements hook_admin_paths().
 */
function payment_admin_paths() {
  $paths = array(
    'payment/*/edit' => TRUE,
  );

  return $paths;
}

/**
 * Implements hook_permission().
 *
 * @see \Drupal\payment\PaymentMethodAccessController
 */
function payment_permission() {
  return \Drupal::service('payment.hook.permission')->invoke();
}

/**
 * Implements hook_hook_info().
 */
function payment_hook_info() {
  return \Drupal::service('payment.hook.hook_info')->invoke();
}

/**
 * Implements hook_field_extra_fields().
 */
function payment_field_extra_fields() {
  return \Drupal::service('payment.hook.field_extra_fields')->invoke();
}

/**
 * Implements hook_element_info().
 */
function payment_element_info() {
  return \Drupal::service('payment.hook.element_info')->invoke();
}

/**
 * Implements hook_entity_bundle_info().
 */
function payment_entity_bundle_info() {
  return \Drupal::service('payment.hook.entity_bundle_info')->invoke();
}
