<?php

/**
 * @file
 *   Hook implementations and general functions.
 */

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Session\AccountInterface;
use Drupal\field\FieldStorageConfigInterface;
use Drupal\field\FieldInstanceConfigInterface;
use Drupal\payment\Entity\PaymentInterface;
use Drupal\payment_reference\PaymentReference;
use Symfony\Cmf\Component\Routing\RouteObjectInterface;

/**
 * Implements hook_page_alter().
 */
function payment_reference_page_alter(&$page) {
  if (\Drupal::request()->attributes->get(RouteObjectInterface::ROUTE_NAME) == 'payment_reference.pay') {
    $skip_regions = array_diff(Element::children($page), array('content'));
    foreach ($skip_regions as $skip_region) {
      $page[$skip_region]['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function payment_reference_entity_extra_field_info() {
  return \Drupal::service('payment_reference.hook.entity_extra_field_info')->invoke();
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function payment_reference_field_config_delete(FieldStorageConfigInterface $field) {
  if ($field->getType() == 'payment_reference') {
    PaymentReference::queue()->deleteByCategoryIdPrefix($field->id());
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function payment_reference_field_instance_config_delete(FieldInstanceConfigInterface $field_instance_config) {
  PaymentReference::queue()->deleteByCategoryId($field_instance_config->id());
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function payment_reference_payment_insert(PaymentInterface $payment) {
  if ($payment->bundle() == 'payment_reference') {
    /** @var \Drupal\payment_reference\Plugin\Payment\Type\PaymentReference $payment_type */
    $payment_type = $payment->getPaymentType();
    PaymentReference::queue()->save($payment_type->getEntityTypeId() . '.' . $payment_type->getBundle() . '.' . $payment_type->getFieldName(), $payment->id());
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function payment_reference_payment_delete(PaymentInterface $payment) {
  PaymentReference::queue()->deleteByPaymentId($payment->id());
}

/**
 * Implements hook_entity_field_access().
 */
function payment_reference_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  if ($field_definition->getType() == 'payment_reference') {
    return (bool) $account->id();
  }
}
