<?php

/**
 * @file
 * Hook implementations and shared functions.
 */

use Drupal\payment\Entity\PaymentInterface;
use Drupal\payment\Plugin\Payment\Status\PaymentStatusInterface;

/**
 * Implements hook_payment_status_set().
 */
function payment_test_payment_status_set(PaymentInterface $payment, PaymentStatusInterface $previous_status = NULL) {
  \Drupal::state()->set('payment_test_payment_status_set', TRUE);
}

/**
 * Implements hook_payment_queue_payment_ids_alter().
 */
function payment_test_payment_queue_payment_ids_alter($field_instance_config_id, $owner_id, array &$payment_ids) {
  \Drupal::state()->set('payment_test_payment_queue_payment_ids_alter', TRUE);
}
