<?php

/**
 * @file
 * Hook implementations and shared functions.
 */

/**
 * Implements hook_payment_form_alter().
 */
function payment_payment_form_alter(array &$elements, array &$form_state, array &$submit) {
  // @see PaymentActionHookAndCallbackWebTestCase.
  $elements['payment_test'] = TRUE;
  $submit[] = 'payment_test';
}

/**
 * Implements hook_payment_validate().
 */
function payment_test_payment_validate(Payment $payment, PaymentMethod $payment_method) {
  if (isset($payment->payment_test_payment_validate)) {
    throw new PaymentValidationException('payment_test');
  }
}

/**
 * Implements hook_payment_status_change().
 */
function payment_test_payment_status_change(Payment $payment, PaymentStatusItem $previous_status_item) {
  $payment->payment_test_payment_status_change = TRUE;
}

/**
 * Implements hook_payment_pre_execute().
 */
function payment_test_payment_pre_execute(Payment $payment) {
  $payment->payment_test_payment_pre_execute = TRUE;
}

/**
 * Implements hook_payment_pre_resume().
 */
function payment_test_payment_pre_resume(Payment $payment) {
  $payment->payment_test_payment_pre_resume = TRUE;
}
