<?php

/**
 * @file
 * Hook implementations and shared functions.
 */

use Drupal\payment\Entity\PaymentInterface;
use Drupal\payment\Plugin\payment\status\PaymentStatusInterface;

/**
 * Implements hook_payment_form_alter().
 */
function payment_payment_form_alter(array &$elements, array &$form_state, array &$submit) {
  // @see PaymentActionHookAndCallbackWebTestCase.
  $elements['payment_test'] = TRUE;
  $submit[] = 'payment_test';
}

/**
 * Implements hook_payment_validate().
 */
function payment_test_payment_validate(Payment $payment, PaymentMethod $payment_method) {
  if (isset($payment->payment_test_payment_validate)) {
    throw new PaymentValidationException('payment_test');
  }
}

/**
 * Implements hook_payment_status_set().
 */
function payment_test_payment_status_set(PaymentInterface $payment, PaymentStatusInterface $previous_status = NULL) {
  \Drupal::state()->set('payment_test_payment_status_set', TRUE);
}

/**
 * Implements hook_payment_pre_execute().
 */
function payment_test_payment_pre_execute(Payment $payment) {
  $payment->payment_test_payment_pre_execute = TRUE;
}
