<?php

/**
 * @file
 *   Hook implementations and general functions.
 */

use Drupal\field\Field;
use Drupal\field\FieldInterface;
use Drupal\payment\Payment;

/**
 * Implements hook_entity_info_alter().
 */
function payment_form_entity_info_alter(&$entity_info) {
  $entity_info['payment']['controllers']['form']['payment_form'] = 'Drupal\payment_form\Entity\PaymentFormController';
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function payment_form_field_entity_insert(FieldInterface $field) {
  if ($field->type == 'payment_form') {
    Payment::typeManager()->clearCachedDefinitions();
    payment_form_field_instance_reference_create($field);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function payment_form_field_entity_update(FieldInterface $field) {
  if ($field->type == 'payment_form') {
    Payment::typeManager()->clearCachedDefinitions();
    payment_form_field_instance_reference_create($field);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function payment_form_field_entity_delete(FieldInterface $field) {
  if ($field->type == 'payment_form') {
    Payment::typeManager()->clearCachedDefinitions();
  }
}

/**
 * Creates a reference to a payment_form field instance.
 *
 * @param \Drupal\field\FieldInterface $field
 *   The payment form field.
 */
function payment_form_field_instance_reference_create(FieldInterface $field) {
  // @todo Convert this to an entity reference once
  //   https://drupal.org/node/1757452 has been fixed.
  $field_name = 'payment_form_field_instance';
  $reference_field = Field::fieldInfo()->getField('payment', $field_name);
  if (!$reference_field) {
    $reference_field = entity_create('field_entity', array(
      'entity_type' => 'payment',
      'id' => $field_name,
      'locked' => TRUE,
      'name' => $field_name,
      'type' => 'text',
    ));
    $reference_field->save();
  }

  $bundle = 'payment_form';
  if (!Field::fieldInfo()->getInstance($field->entity_type, $bundle, $field_name)) {
    $reference_instance = array(
      'field_uuid' => $reference_field->uuid(),
      'entity_type' => $field->entity_type,
      'bundle' => $bundle,
      'label' => t('Payment form field instance ID'),
    );
    entity_create('field_instance', $reference_instance)->save();
  }
}
